
services:
  web: 
    build:
      context: .
      dockerfile: Dockerfile-production
      args:
        - NEXT_PUBLIC_API_BASE=https://didomran.ir/api/v1

    environment:
      - NEXT_PUBLIC_API_BASE=https://didomran.ir/api/v1
    ports:
      - "3000:3000"
    working_dir: /app
