FROM node:22-alpine

WORKDIR /app

RUN npm install -g pnpm

COPY package.json /app

RUN pnpm install

COPY . /app

ARG NEXT_PUBLIC_API_BASE
ENV NEXT_PUBLIC_API_BASE=$NEXT_PUBLIC_API_BASE

RUN pnpm build && pnpm start

