
services:
  web: 
    build:
      context: .
      dockerfile: Dockerfile-production
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - "3000:3000"
    env_file:
      - ".env"
    working_dir: /app
