import type { Metadata } from "next";
import "./globals.css";
import Header from "@/app/components/header/Header";
import { ToastContainer } from "react-toastify";
import "react-loading-skeleton/dist/skeleton.css";
import Footer from "./components/footer/Footer";
import { Suspense } from "react";
import { MantineProvider } from "@mantine/core";

export const metadata: Metadata = {
    title: "دید عمران",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="fa" dir="rtl">
        <body
            className={` antialiased overflow-x-clip bg-white100`}
        >
        <Header/>
        <Suspense>
            <MantineProvider>
                <main className="pt-[77px] max-w-[1440px] mx-auto">{children}</main>
            </MantineProvider>
        </Suspense>
        <ToastContainer position="top-center"/>
        <Footer/>
        </body>
        </html>
    );
}
