import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/app/components/header/Header";
import { ToastContainer } from "react-toastify";
import "react-loading-skeleton/dist/skeleton.css";
import Footer from "./components/footer/Footer";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="fa" dir="rtl">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-x-clip bg-white100`}
            >
                <Header />
                <main className="pt-[77px] max-w-[1440px] mx-auto ">{children}</main>
                <ToastContainer position="top-center" />
                <Footer />
            </body>
        </html>
    );
}
